# MINOR PROJECT:

Make a Heart Disease Predictive Model to predict on the “target” column of the dataset

Given csv file heart.csv

In [1]:
import pandas as pd
import numpy as np
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split
import tensorflow as tfl

In [2]:
df=pd.read_csv('E:/heart.csv')

In [3]:
df

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0     63    1   3       145   233    1        0      150      0      2.3   
1     37    1   2       130   250    0        1      187      0      3.5   
2     41    0   1       130   204    0        0      172      0      1.4   
3     56    1   1       120   236    0        1      178      0      0.8   
4     57    0   0       120   354    0        1      163      1      0.6   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
298   57    0   0       140   241    0        1      123      1      0.2   
299   45    1   3       110   264    0        1      132      0      1.2   
300   68    1   0       144   193    1        1      141      0      3.4   
301   57    1   0       130   131    0        1      115      1      1.2   
302   57    0   1       130   236    0        0      174      0      0.0   

     slope  ca  thal  target  
0        0   0     1       1  
1        0   0     2       1  
2        2   0     2       1  
3        2   0     2       1  
4        2   0     2       1  
..     ...  ..   ...     ...  
298      1   0     3       0  
299      1   0     3       0  
300      1   2     3       0  
301      1   1     3       0  
302      1   1     2       0  

[303 rows x 14 columns]

In [4]:
df.shape

(303, 14)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 303 entries, 0 to 302
Data columns (total 14 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   age       303 non-null    int64  
 1   sex       303 non-null    int64  
 2   cp        303 non-null    int64  
 3   trestbps  303 non-null    int64  
 4   chol      303 non-null    int64  
 5   fbs       303 non-null    int64  
 6   restecg   303 non-null    int64  
 7   thalach   303 non-null    int64  
 8   exang     303 non-null    int64  
 9   oldpeak   303 non-null    float64
 10  slope     303 non-null    int64  
 11  ca        303 non-null    int64  
 12  thal      303 non-null    int64  
 13  target    303 non-null    int64  
dtypes: float64(1), int64(13)
memory usage: 33.3 KB


In [6]:
df["target"].value_counts()

1    165
0    138
Name: target, dtype: int64

In [7]:
y = df["target"]

In [8]:
x = df.drop('target',axis='columns')

In [9]:
print(x)

     age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0     63    1   3       145   233    1        0      150      0      2.3   
1     37    1   2       130   250    0        1      187      0      3.5   
2     41    0   1       130   204    0        0      172      0      1.4   
3     56    1   1       120   236    0        1      178      0      0.8   
4     57    0   0       120   354    0        1      163      1      0.6   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
298   57    0   0       140   241    0        1      123      1      0.2   
299   45    1   3       110   264    0        1      132      0      1.2   
300   68    1   0       144   193    1        1      141      0      3.4   
301   57    1   0       130   131    0        1      115      1      1.2   
302   57    0   1       130   236    0        0      174      0      0.0   

     slope  ca  thal  
0        0   0     1  
1        0   0     2  
2        2   0    

In [10]:
x_train,x_test,y_train, y_test = train_test_split(x,y,test_size=0.2)

In [11]:
print(x.shape)

(303, 13)


In [12]:
from tensorflow.keras.utils import to_categorical

In [13]:
y=to_categorical(y)

In [14]:
y.shape

(303, 2)

# Specify the architecture

In [15]:
from tensorflow.keras.layers import Dense
from tensorflow.keras.models import Sequential

In [16]:
model=Sequential()

In [17]:
model.add(Dense(130,activation='relu', input_shape=(13,)))
model.add(Dense(15, activation='relu',))
model.add(Dense(2, activation='softmax',))

# Compiling the model

In [18]:
model.compile(optimizer='adam',loss='categorical_crossentropy',metrics=['accuracy'])

# Training the model

In [19]:
model.fit(x,y,epochs=10)

Epoch 1/10
10/10 [==============================] - 0s 960us/step - loss: 3.2449 - accuracy: 0.4785
Epoch 2/10
10/10 [==============================] - 0s 698us/step - loss: 1.5340 - accuracy: 0.4917
Epoch 3/10
10/10 [==============================] - 0s 802us/step - loss: 0.9834 - accuracy: 0.5347
Epoch 4/10
10/10 [==============================] - 0s 698us/step - loss: 0.7579 - accuracy: 0.6469
Epoch 5/10
10/10 [==============================] - 0s 798us/step - loss: 0.7585 - accuracy: 0.6040
Epoch 6/10
10/10 [==============================] - 0s 902us/step - loss: 0.8034 - accuracy: 0.6370
Epoch 7/10
10/10 [==============================] - 0s 898us/step - loss: 0.7027 - accuracy: 0.6601
Epoch 8/10
10/10 [==============================] - 0s 898us/step - loss: 0.5937 - accuracy: 0.7327
Epoch 9/10
10/10 [==============================] - 0s 804us/step - loss: 0.5438 - accuracy: 0.7459
Epoch 10/10
10/10 [==============================] - 0s 798us/step - loss: 0.5032 - accuracy: 0.7525

# Testing the model

In [20]:
test_parameters1=pd.DataFrame({'age':[68],'sex':[1],'cp':[0],'trestbps':[144],'chol':[193],'fbs':[1],'restecg':[1],'thalach':[141],'exang':[0],'oldpeak':[3.4],'slope':[1],'ca':[2],'thal':[3]})

In [21]:
test_parameters2=pd.DataFrame({'age':[37],'sex':[1],'cp':[2],'trestbps':[130],'chol':[250],'fbs':[0],'restecg':[1],'thalach':[187],'exang':[0],'oldpeak':[3.5],'slope':[0],'ca':[0],'thal':[2]})

In [22]:
prediction1=model.predict(test_parameters1)

In [23]:
prediction1

array([[0.7922925 , 0.20770757]], dtype=float32)

In [24]:
prediction1[0]

array([0.7922925 , 0.20770757], dtype=float32)

In [25]:
np.argmax(prediction1[0])

0

In [26]:
prediction2=model.predict(test_parameters2)

In [27]:
prediction2

array([[0.12599647, 0.8740035 ]], dtype=float32)

In [28]:
prediction2[0]

array([0.12599647, 0.8740035 ], dtype=float32)

In [29]:
np.argmax(prediction2[0])

1